# Generated by Django 4.2.14 on 2024-07-30 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_website_alert_website_owner_website_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringresult',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.website'),
        ),
    ]
