# Generated by Django 4.2.14 on 2024-07-30 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='webhook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
